# This is a basic workflow to help you get started with Actions

name: dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

env:
  BUILD: Herodotus
  VERSION: DevEdition
  COMMON_NAME: ${BUILD}-${VERSION}-build${GITHUB_RUN_NUMBER}

jobs:

  FTBQuestsProcessor: 
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
      
      - name: Run FTB Quests lang processor
        run: python runners/ftbq_lang_processor.py

      - name: Commit processor changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: friendlyhj
          author_email: youyi580@qq.com
          message: "ftbq lang processor changes (github action)"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: FTBQuestsProcessor

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
    # Runs a single command using the runners shell
      - name: Run build.sh
        run: bash runners/build.sh
    #Upload the artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
        # Artifact name
          name: Herodotus-dev
        # A file, directory or wildcard pattern that describes what to upload
          path: artifacts

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download the Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: Herodotus-dev
          path: modpack

      - name: Unzip the modpack
        run: unzip -o ${GITHUB_WORKSPACE}/modpack/${COMMON_NAME}.zip

      - name: Download Modpack Downloader CLI
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: Nincraft/ModPackDownloader
          tag: 0.6.1
          path: downloader
          file: ModpackDownloader-cli-0.6.1.jar

      - name: Download GML
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: xmdhs/gomclauncher
          tag: v1.3.9
          path: gml
          file: gml-linux.gz

      - name: Unzip GML
        run: sudo gzip -d ${GITHUB_WORKSPACE}/gml/gml-linux.gz

      - name: Grant Premission for GML
        run: | 
          sudo chmod +x ${GITHUB_WORKSPACE}/gml/gml-linux

      - name: Download Minecraft 1.12.2
        run: |
          cd gml
          sudo ./gml-linux -downver 1.12.2 -type "vanilla" -independent=f

      - name: Load Modpack Stuff
        run: sudo mv ${GITHUB_WORKSPACE}/.minecraft/* ${GITHUB_WORKSPACE}/gml/.minecraft/

      - name: Set launcher_profiles.json
        run: sudo bash ${GITHUB_WORKSPACE}/runners/set_launcher_profiles.sh

      - name: Download Forge 14.23.5.2854 Installer
        run: sudo wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar -O ${GITHUB_WORKSPACE}/gml/forge-1.12.2-14.23.5.2854-installer.jar

      - name: Download Forge Install Bootstrapper
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: bangbang93/forge-install-bootstrapper
          tag: 0.0.0
          path: gml
          file: forge-install-bootstrapper.jar

      - name: Install Forge 14.23.5.2854
        run: |
          cd gml
          sudo java -cp "forge-install-bootstrapper.jar:forge-1.12.2-14.23.5.2854-installer.jar" com.bangbang93.ForgeInstaller ./.minecraft/

      - name: Download Mods
        run: |
         tree -a
         sudo java -jar ${GITHUB_WORKSPACE}/downloader/ModpackDownloader-cli-0.6.1.jar -manifest ${GITHUB_WORKSPACE}/modpack/manifest.json -folder ${GITHUB_WORKSPACE}/gml/.minecraft/mods

      - name: Install Autostop
        run: sudo mv ${GITHUB_WORKSPACE}/runners/autostop-1.0.jar ${GITHUB_WORKSPACE}/gml/.minecraft/mods

      - name: Run modpack
        run: sudo ./gml/gml-linux -run 1.12.2-forge-14.23.5.2854 -username tester -ram 6144
